### ISSUE TITLE
Cant compile on MacOS catalina 10.15 with this error

### ISSUE THREAD

**Issue by codingwithflitz** [blocknodetech/blocknode#6]
`CXX      libbitcoin_common_a-accumulators.o
accumulators.cpp:22:15: error: call to 'distance' is ambiguous
    int pos = distance(zerocoinDenomList.begin(), find(zerocoinDenomList.begin(), zerocoinDenomList.end(), denomination));
              ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:608:1: note: candidate function [with _InputIter =
      std::__1::__wrap_iter<const libzerocoin::CoinDenomination *>]
distance(_InputIter __first, _InputIter __last)
^
/usr/local/include/boost/iterator/distance.hpp:49:9: note: candidate function [with SinglePassIterator = std::__1::__wrap_iter<const libzerocoin::CoinDenomination *>]
        distance(SinglePassIterator first, SinglePassIterator last)
        ^
1 error generated.
make[2]: *** [libbitcoin_common_a-accumulators.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
Vins-MacBook-Pro:testcoin vin$
